# REQ/REP EVENT STATUS
REGISTER_REQ = "REGISTER_REQ"
REGISTER_REP = "REGISTER_REP"

TASK_REQ = 'TASK_REQ'
TASK_REP = 'TASK_REP'

RESULT_REQ = 'RESULT_REQ'
RESULT_REP = 'RESULT_REP'

FAILURE_REQ = 'FAILURE_REQ'
FAILURE_REP = 'FAILURE_REQ'

SHUTDOWN_REQ = 'SHUTDOWN_REQ'
SHUTDOWN_REP = 'SHUTDOWN_REP'

# DEALER/ROUTER EVENT STATUS
REGISTERATION = 'REGISTERATION'  # sender: worker; receiver: dispatcher
RESULT = 'RESULT'   # sender: worker; receiver: dispatcher
TASK = 'TASK'   # receiver: worker; sender: dispatcher
SHUTDOWN = 'SHUTDOWN' # sender: worker; receiver: dispatcher
FAILURE = 'FAILURE'

# REDIS
CHANNEL_NAME = 'TASK'

# TASK STATUS
TASK_COMPLETE = "COMPLETED"
TASK_FAILURE = "FAILED"
TASK_QUEUED = 'QUEUED'
TASK_RUNNING = 'RUNNING'
